language: ruby
before_script:
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get install libavformat-dev libavfilter-dev libavdevice-dev ffmpeg
rvm:
  - 2.3.1
  - 3.2.1
cache:
  - bundler
