language: ruby
before_script:
  - gem install bundler
  - sudo add-apt-repository ppa:jonathonf/ffmpeg-4
  - sudo apt update
  - sudo apt-get install ffmpeg
  - ffmpeg -version
rvm:
  - 2.6.0
  - 3.2.1
cache:
  - bundler
script:
  - bundle exec rspec
